plugins {
    alias(libs.plugins.multiplatform).apply(false)
    alias(libs.plugins.compose).apply(false)
    alias(libs.plugins.android.application).apply(false)
    alias(libs.plugins.android.library).apply(false)
    alias(libs.plugins.buildConfig).apply(false)
    alias(libs.plugins.kotlinx.serialization).apply(false)
    alias(libs.plugins.composePlugin).apply(false)
    alias(libs.plugins.detekt).apply(false)
    alias(libs.plugins.convention.detekt).apply(false)
    alias(libs.plugins.convention.compose).apply(false)
    alias(libs.plugins.convention.feature).apply(false)
    alias(libs.plugins.convention.core).apply(false)
    alias(libs.plugins.convention.application).apply(false)
}
